### ISSUE TITLE
CSS color like manipulation

### ISSUE THREAD

**Issue by kuon** [mdgriffith/elm-color-mixing#3]
It would be handy to have the equivalent adjustment as https://drafts.csswg.org/css-color-4/#modifying-colors

Right now, we can adjust each HSL component by an absolute value, like `y = current + x` it would be handy to add `y = current * x` and `y = x` . And also support RGBA channels.

**Comment by mdgriffith** [comment]
Hello!

So, you can break out individual channels using the standard `Color` library doing something like this:

```elm
let
    -- deconstruct a color into it's channels
    {red, green, blue, alpha} = Color.toRgb Color.red

in
    -- reconstruct a color, adding 1 to the red channel.
    Color.rgba (red + 1) green blue alpha

```

Is that along the lines of what you're thinking?

**Comment by kuon** [comment]
Yes, something like

```elm
multRed : Float -> Color -> Color
multRed x =
    let
        -- deconstruct a color into it's channels
        {red, green, blue, alpha} = Color.toRgb Color.red

    in
        -- reconstruct a color, adding 1 to the red channel.
        Color.rgba (red * x) green blue alpha

setRed : Float -> Color -> Color
setRed x =
    let
        -- deconstruct a color into it's channels
        {red, green, blue, alpha} = Color.toRgb Color.red

    in
        -- reconstruct a color, adding 1 to the red channel.
        Color.rgba (x) green blue alpha

addRed : Float -> Color -> Color
addRed x =
    let
        -- deconstruct a color into it's channels
        {red, green, blue, alpha} = Color.toRgb Color.red

    in
        -- reconstruct a color, adding 1 to the red channel.
        Color.rgba (red + x) green blue alpha
```

A few of them are present, like `addSaturation` is actually present as `saturate`.

The new CSS4 `color` directive let us do things like `color(red s(5%))` to set the S channel of red to 5%, `color(red s(+ 5%))` to add 5% saturation or `color(red s(* 5%))` to multiply saturation by 0.05.

I don't know what would be the best approach, the `multChannel, addChannel, setChannel` seems a bit cumbersome.

We need a syntax that can be easily chained, like in CSS `color(red l(- 20%) s(- 10%) a(80%))` produces desaturated and darkened red with a bit of transparency. (`#cc1414` with 0.8 alpha)

**Comment by mdgriffith** [comment]
Cool, yeah I can see that some finer grained focus on channel functions would be nice for chaining.

How about something like this:


```elm
mapRed : (Float -> Float) -> Color -> Color
mapRed fn x =
    let
        {red, green, blue, alpha} = Color.toRgb Color.red

    in
        Color.rgba (fn red) green blue alpha
```


```elm

Color.blue
    |> Color.Mixing.mapRed ((*) 2)

Color.blue
    |> Color.Mixing.mapRed (always 2)

```

Maybe actually creating a new module called `Color.Mixing.Channel` and have `Color.Mixing.Channel.red`, `Color.Mixing.Channel.hue`, etc.  all of which take a function and apply it to a given channel.

Though that doesn't cover percentages, which seem super useful in this case.

That can probably be covered by a little helper function for percent:

```elm
-- %80 -> 100 -> 80
percent : Float -> Float -> Float
```


```elm

-- set red channel to 80% of what it currently is
Color.blue
    |> Color.Mixing.mapRed (percent 80)

-- Do more involved math if necessary
Color.blue
    |> Color.Mixing.mapRed (\r ->  (percent 80 r) * r)

```

**Comment by kuon** [comment]
Actually the percentage notation is absolute. Which means `color(red s(- 50%) s(- 10%))` is actually equivalent to `color(red s(- 60%))` and not `color(red s(- 55%))`

**Comment by mdgriffith** [comment]
Ok, interesting, so that means that the % is not related to the existing channel value, but to the full range?

As in, `s(+ 5%)` means `current saturation + 5%`, and not `current saturation + 5% of current saturation`?

**Comment by kuon** [comment]
Yes, it is related to full range. `s(+ 5%)` is "plus 5% saturation of full range" So if you have a super dark color with lightness at nearly 0, if you  do `l(+ 5%)` you will have a color at near `5%` lightness.

**Comment by kuon** [comment]
Any update on this? Do you want help?

**Comment by mdgriffith** [comment]
Hey,

No update, but I'm willing to take a look now.

Ok, so for this we want:

  * Mapping a function to a color/hsl channel `mapRed`, `mapSaturation`, etc.
  * Some sort of absolute percentage manipulation.

Something like:

```elm
Color.red
    |> Color.Mixing.mapRedPercent ((+) 0.5)  -- s(+ 50%)
        
```
That look good?

**Comment by kuon** [comment]
Maybe we could do something like:

```elm
Color.red
    |> Color.Mixing.Adjust.s ((+) 0.5) -- saturate by adding 0.5 to saturation channel
    |> Color.Mixing.Adjust.a ((=) 0.8) -- set alpha channel to 0.8
    |> Color.Mixing.Adjust.r ((*) 0.2) -- mult current red channel by 0.2
```

I think short method names are ok, so we can import them if we want and do:

```elm
red |> s((+) 0.5) |> a((=) 0.2)
```

This would be close to the current CSS syntax.

**Comment by kuon** [comment]
To clarify, given a color with `rgb` or `hls` channel, the operator would act as follow:

```elm
-- example with s channel, same goes for r, g, b, h, l, s and a channels
s((+) x) -- s = clamp(s + x, 0, 1)
s((-) x) -- s = clamp(s - x, 0, 1)
s((*) x) -- s = clamp(s * x, 0, 1)
s((=) x) -- s = clamp(x, 0, 1)
```

**Comment by kuon** [comment]
Btw, I can make a PR if you want.

**Comment by kuon** [comment]
Also in my example above, I guess `(=)` is `always`

**Comment by mdgriffith** [comment]
So, I will be honest, I'm not really a fan of short names :)  Simply because if you know them, that's great, but if you don't it can be incredibly frustrating.

Doesn't prevent you from making aliases though!

I'm going to go ahead with `mapRed` and `mapRedPercent`. I should have code up in a moment

**Comment by kuon** [comment]
What difference do you plan between mapRed and mapRedPercent? The second one takes a value between 0 and 100?

**Comment by mdgriffith** [comment]
Yeah, basically.  Though I was thinking actually taking a value between 0.0 and 1.0, because that seems to be the standard for percentage in elm.

**Comment by mdgriffith** [comment]
So,

`mapRed` takes a function that receives the raw red channel value and returns a new raw red channel value.

`mapRedPercent` takes a function that receives the current red channel percentage and returns a new red channel percentage.

**Comment by kuon** [comment]
Haa, so mapRed is between 0,255 and mapRedPercent is between 0 and 1.0. Ok, good, got it.

**Comment by mdgriffith** [comment]
Ok, published! 

http://package.elm-lang.org/packages/mdgriffith/elm-color-mixing/1.1.0/Color-Mixing

**Comment by kuon** [comment]
That was fast. I'd add an example using `always` in the doc to set the value.

Eg:

```elm
Color.red
|> Color.Mixing.mapRedPercent ((always) 0.5)
```

Let's make it obvious how it works:)

**Comment by mdgriffith** [comment]
Good call!  done :)
